/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/NYDyUGoHDaq
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import { ChatMessage } from "@/components/ChatMessage"

export function Chat() {
  return (
    <div className="flex flex-col h-screen w-full max-w-[1024px] border border-gray-400 rounded-lg">
      <div className="flex-1 overflow-auto p-4 space-y-4 w-full">
        <ChatMessage
          isAI={true}
          avatarSrc="/placeholder-user.jpg"
          avatarFallback="JD"
          name="John Doe"
          message="Hey there! How's it going?"
        />
        <ChatMessage
          isAI={false}
          avatarSrc="/placeholder-user.jpg"
          avatarFallback="JD"
          name="You"
          message="Pretty good, thanks for asking!"
        />
        <ChatMessage
          isAI={true}
          avatarSrc="/placeholder-user.jpg"
          avatarFallback="JD"
          name="John Doe"
          message="Glad to hear it! Did you catch the game last night?"
        />
        <ChatMessage
          isAI={false}
          avatarSrc="/placeholder-user.jpg"
          avatarFallback="JD"
          name="You"
          message="No, I missed it. What happened?"
        />
      </div>
      <div className="border-t p-2 flex items-center gap-2">
        <Textarea
          placeholder="Type your message..."
          className="flex-1 resize-none rounded-lg p-2 border border-muted focus:border-primary focus:ring-primary"
        />
        <Button variant="ghost" size="icon" className="rounded-full">
          <SendIcon className="w-5 h-5" />
          <span className="sr-only">Send</span>
        </Button>
      </div>
    </div>
  )
}

function SendIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m22 2-7 20-4-9-9-4Z" />
      <path d="M22 2 11 13" />
    </svg>
  )
}
